---
version: "3.0"
services: 
  app:
    build:
      context: .
  relay:
    image: nginx:1.18-alpine
    volumes: 
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'