Vagrant.configure(2) do |config|
  config.vm.define 'nodeploy-devenv'
  config.vm.box = 'hashicorp/bionic64'

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'devenv.yml'
  end
end