---
- name: Get NodeSource APT GPG key
  apt_key: 
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: yes

- name: Add NodeSource APT repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodesource_version }}.x {{ ansible_distribution_release }} main
    state: present
  become: yes

- name: Install NodeJS
  apt:
    name: "{{ nodesource_packages|flatten }}"
    state: "{{ nodesource_packages_state }}"
    update_cache: yes
  become: yes